export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  NOTHING_TO_PERFORM: "NOTHING_TO_PERFORM",
  INVALID_ID: "INVALID_ID",

  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

  INVALID_INPUT: "INVALID_INPUT",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  TXN_NOT_FOUND: "TXN_NOT_FOUND",
  TXN_INVALID_ACCOUNT: "TXN_INVALID_ACCOUNT",
  TXN_SYNC_CONFLICT: "TXN_SYNC_CONFLICT",

  DB_ERROR: "DB_ERROR",
};
